version: '3.4'

services:

  frontend-api-lb:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend-api
    ports:
      - "5000:5000"
    networks: 
      - backend
      
  frontend-api:
    image: demo365.api
    environment:
      REPOSITORY_URL: 'http://internal-api-lb:5100'
    #ports:
    #  - "5200:80"
    expose:
      - "80"
    depends_on:
      - repository-api
    networks: 
      - backend

  fakesource-loader:
    image: demo365.fakesource
    environment:
      REPOSITORY_URL: 'http://internal-api-lb:5100'
    depends_on:
      - repository-api
    networks: 
      - backend

  internal-api-lb:
    image: nginx:latest
    volumes:
      - ./nginx-internal.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - repository-api
    expose:
      - "5100"
    #ports:
    #  - "5100:5100"
    networks: 
      - backend
      
  repository-api:
    image: demo365.repository
    environment:
      DB_CONNECTION: 'Data Source=repository-db;Database=demo365;User Id=root;Password=Demo365!;SSL Mode=None'
    expose:
      - "80"
    #ports:
    #  - "5100:80"
    depends_on:
      - repository-db
    networks: 
      - backend

  repository-db:
    image: demo365.repository.db
    restart: always
    environment:
      MYSQL_DATABASE: 'demo365'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'Demo365!'
      MYSQL_ROOT_PASSWORD: 'Demo365!'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - data:/var/lib/mysql
    networks: 
      - backend

volumes:
  data: 
  
networks:
  backend:
    driver: "bridge"      
